
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Remplacez ces valeurs par celles de votre Supabase auto-hébergé
const SUPABASE_URL = "https://votre-domaine-supabase.example.com";
const SUPABASE_PUBLISHABLE_KEY = "votre-cle-anon-publique";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
