// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbqgbammyhcijweyvgvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1icWdiYW1teWhjaWp3ZXl2Z3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDQ3NzAsImV4cCI6MjA1ODk4MDc3MH0.D_7E_3ymWqXDguqX1Ldg3GFanlzM-YS-MoKPhxYC570";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);